---
title: "Problem Set 3"
subtitle: "Due date: 25 September"
format: 
  html:
    self-contained: true
toc: true
editor: visual
execute: 
  warning: false
bibliography: references.bib
editor_options: 
  chunk_output_type: inline
---

Please upload your completed assignment to the ELMs course site (under the assignments menu) and to your class Github repository. You need to upload both your Quarto document (with R code, as needed) and its rendered output (either as a PDF or HTML file).

**Total points: 30**

```{r}
dem_wealth_df <- readr::read_csv("http://svmiller.com/extdata/democracy-income-1950.csv") |> 
  dplyr::transmute(iso3c, country, gdp_per_cap = wbgdp2011est / wbpopest, democracy_score = xm_qudsest)
```

The `dem_wealth_df` data set (taken from the wonderful Dr Steven V Miller's [blog post](https://svmiller.com/blog/2023/09/democracy-income-correlation-analysis/)) will help us explore the relationship between a country's level of democracy and its citizens' wealth in 1950. It is a replication of [Lipset (1959)](https://www.cambridge.org/core/journals/american-political-science-review/article/abs/some-social-requisites-of-democracy-economic-development-and-political-legitimacy1/26559429359F42D3E9B8BC82CA65546A). Miller uses Xavier Marquez's [measure for democracy](https://www.cambridge.org/core/journals/political-analysis/article/democratic-compromise-a-latent-variable-analysis-of-ten-measures-of-regime-type/2A6B2BBA6F80367644F2C5007E1CFC29). This is a great (if complicated) measure. For this problem set, you only need to know that a country's level of democracy increases with its "democracy score".

## Question 1

### Part A

*Points: 2*

> **Using the `dem_wealth_df` data frame loaded in above, produce a scatter plot of the variables `democracy_score` and `gdp_per_cap` (with `gdp_per_cap` as the dependent variable on the y-axis). Professionally format your graph.**
>
> ``` r
> {r}
> ggplot(dem_wealth_df, aes(x = democracy_score, y = gdp_per_cap)) +
>     geom_point() +
>     theme_bw() +
>     theme(plot.title = element_text(face = "bold"),
>           plot.title.position = "panel") +
>     labs(title = "Democracy Score and GDP per Capita",
>          x = "Democracy Score",
>          y = "GDP per capita (USD)"
>     ) +
>     scale_x_continuous(labels = scales::label_comma())
> ```
>
> ``` r
> {r}
> ggplot(dem_wealth_df, aes(x = democracy_score, y = gdp_per_cap)) +
>     geom_text(aes(label = country)) +
>     theme_bw() +
>     theme(plot.title = element_text(face = "bold"),
>           plot.title.position = "panel") +
>     labs(title = "Democracy Score and GDP per Capita",
>          x = "Democracy Score",
>          y = "GDP per capita (USD)"
>     ) +
>     scale_x_continuous(labels = scales::label_comma())
> ```
>
> ### Part B

*Points: 3*

> **Describe the scatter plot. Note suspected outliers if any exist (a visual inspection will suffice for this question).**
>
> > The overall pattern of the scatterplot is that as a country's democracy score increases, GDP per capita tends to increase as well. The direction of the relationship is positive. I can tell because both variables move in the same direction (increasing when the other increases). Given the correlation coefficient of 0.7008677, I would also classify the relationship between the two variables as strong positive.
> >
> > Despite the overall pattern, I suspect there may be some outliers in the dataset. For example, I suspect that Venezuela is an outlier. Venezuela has a democracy score of -0.118, yet has a GDP per capita of 9749.780. That is unusual relative to other countries with similar democracy scores as countries in the sample with a democracy score below zero tended to have GDP per capitas below around 7,500. Furthermore, Venezuela's GDP per capita is even slightly higher than countries with high democracy scores like Iceland, the Netherlands, and Belgium. I also suspect that the United States and Switzerland are outliers. Despite not having the highest democracy score, the United States has a GDP per capita of 17,171.392, the highest GDP per capita of the sampled countries. What's more, as the US has a democracy score comparable to Ireland, the US should have a relatively similar GDP per capita; yet, the US's GDP per capita is more than double that of Ireland's. Similarly, Switzerland has a democracy score of 1, but has a GDP per capita that far outpaces other sample countries with a similar democracy score.

## Question 2

*Points: 2*

> Calculate the correlation coefficient between `democracy_score` and `gdp_per_cap`. What does it tell you about the relationship between a country's level of democracy and its citizens' wealth?
>
> ``` r
> cor(dem_wealth_df$democracy_score, dem_wealth_df$gdp_per_cap, use = "complete.obs")
> ```
>
> The correlation coefficient is 0.7008677. This tells me that there is a strong positive correlation between a country’s level of democracy and its citizens' wealth. Specifically, this tells me that as a country’s democracy score, and thus, level of democracy increases, on average, its citizens’ wealth also increases. Thus, among the sampled countries, more democratic countries tend to have citizens with higher levels of wealth.

## Question 3

I would like to know whether individuals with higher levels of education tend to pay greater levels of attention to politics than those with lower levels of education.

### Part A

*Points: 5*

> Using the `nes` data set in the `polisciols` R package, construct a cross-tab of the relationship between `attention_to_politics` and `education`. Focus only on those respondents who provided answers (filter out "Refused", "Don't know", and missing responses).
>
> ``` r
> datasummary_crosstab(attention_to_politics ~ education, data = nes)
> ```

### Part B

*Points: 3*

> **Describe the relationship between these two variables (if one exists).**
>
> Those with some post-high school education but no bachelor’s degree, a bachelor’s degree, and a graduate degree tended to pay considerable attention to politics, answering “always”, more often than those with a high school credential or less than a high school credential.
>
> Those with some post-high school education, but no bachelor’s degree tended to pay the most attention to politics than the individuals of other educational attainment levels. Specifically, based on percentage and count, those with some post-high school education, but no bachelor’s degree answered that they “always” pay attention to politics more frequently than other groups. However, the counts of those with “some high school, but no bachelor’s, a bachelor’s, and a graduate degree who answered “always” were comparable at 590, 499, 512 respectively.
>
> The relationship between education and the level of attention paid to politics is a bit unclear. Those with a minimum of some post-high school education are shown to pay attention to politics more than those with only a high school credential or less than a high school credential. Yet, the relationship between the two variables is not perfectly linear as those with the highest level of educational attainment (graduate degrees) did not respond “always” at the highest rate. Similarly, those with a bachelor’s degree did not respond that they paid more attention to politics than those with some post-high school, no bachelor’s degree.
>
> Furthermore, the analysis of the relationship between the variables could be affected by the fact that there were considerably more respondents with some post-high school, no bachelor’s degree compared to those with a high school credential or less than high school credential.

## Question 4

*Points: 5*

**I hypothesize that US voters who identify as being religious are less likely to support Federal government funding of scientific research. To test this, I run a survey of a representative sample of the US voting population. I ask respondents to indicate how often they attend religious ceremonies as a proxy measure of how strongly they identify as religious. They can answer: never, only for significant events, or regularly. Next, I ask respondents whether they think the Federal government's funding of scientific research is "too little", "about right", or "too much".**

> **Describe how you would construct a cross-tab to evaluate my hypothesis. Which responses (religious identification or support for Federal funding) would you compare within? Relatedly, which would you vary? Finally, what statistics would you use to make your comparisons?**
>
> I would place the variable, support for federal government funding of scientific research along the left side of the crosstab, forming the rows of the crosstab. I would place the variable for religious identification along the top of the crosstab, forming the columns of the crosstab. Based on the hypothesis, I would expect to see that those who never go to church would answer that the federal government gives too little or about the right amount of funding for scientific research more than the other respondent groups. I would similarly expect that those who regularly go to church would answer most frequently that the federal government gives too much funding for scientific research.
>
> To test the hypothesis, I would examine the rows for each response for views on federal funding for scientific research (“too little”, “about right”, or “too much”) to examine the general distribution of responses, focusing on the percentages. I would examine the row displaying the counts and percentages for the response “too little”. I would examine if those who responded that they did not go to church frequently responded more frequently that the federal government gave too little or about the right amount of funding for scientific research and those who went to church regularly responded that the federal government gave too much funding.
>
> I would also compare the counts and percentages of respondents within the religious identification column, examining the distribution of the proportion of those who regularly attend church who selected each answer in order to see what answers did those who attend select most frequently out of all of the choices. I would also compare the percentages of those who regularly attend church against the frequency of response of those who are less religious.

## Question 5

Let's return to our original question of the relationship between democracy and individuals' wealth.

### Part A

*Points: 2*

> **Create two new variables based on a country's level of democracy, and its citizens' wealth. For the democracy variable, split countries into three categories: `autocracy` if they score in the lowest third of democracy scores, `hybrid` if they score in the middle third, and `democracy` if they score in the highest third. Similarly, for the wealth variable, split countries into three categories: `low income` if they score in the lowest third of GDP per capita, `middle income` if they score in the middle third, and `high income` if they score in the highest third.**

``` r
dem_wealth_df$income_category <- ifelse(dem_wealth_df$gdp_per_cap > 0 & dem_wealth_df$gdp_per_cap < 6000,"Low Income", ifelse(dem_wealth_df$gdp_per_cap >= 6000 & dem_wealth_df$gdp_per_cap < 12000, "Middle Income",ifelse(dem_wealth_df$gdp_per_cap >= 12000 & dem_wealth_df$gdp_per_cap < 18000, "High Income", NA)))

dem_wealth_df$democracy_category <- ifelse(dem_wealth_df$democracy_score > -1 & dem_wealth_df$democracy_score < 0,"Autocracy", ifelse(dem_wealth_df$democracy_score >= 0 & dem_wealth_df$democracy_score < 1, "Hybrid",ifelse(dem_wealth_df$democracy_score >= 1 & dem_wealth_df$democracy_score < 2, "Democracy", NA)))
```

### Part B

*Points: 3*

> **Create a cross-tab.**
>
> ``` r
> datasummary_crosstab(democracy_category ~ income_category, data = dem_wealth_df)
> ```

### Part C

*Points: 5*

> **Describe the relationship between these variables.**

From my previous calculation of the corelation coefficient, I know that there is a strong positive relationship between the variables, a country’s level of democracy (as defined by its democracy score and related grouping) and its citizens wealth (as defined by GDP per capita). (However, the considerable strength of the relationship may be partially the result of skew due to outliers).

Based on the crosstab, autocracies tended more often than other countries with more democratic levels of government, to have lower income citizens. Specifically, 15 out of 17 or 88.2% of low income countries were autocratic. Conversely, only two middle income countries were low income.

In the sample, out of the democracies, six were high income. Relatedly, zero high income countries were autocratic and all six high income countries were democracies, suggesting a strong relationship between high levels of democracy and a higher GDP per capita.

Furthermore, out of the democracies, only 2 were low income, while 12 were middle income. Out of the low income countries, 10 were hybrid. While 1- hybrid states were low income, only one was middle income and none were high income. Ultimately the distribution of the data suggests that states with considerably low democracy scores, specifically autocracies, were more likely to be lower income, and thus, have lower levels of citizen wealth. However, the majority of democracies were middle and high income, with all high income countries being democracies. Thus, this confirms the findings of the correlation coefficient in regard to the strong positive relationship between level of democracy and GDP per capita: as a country's score and level of democratization increases to that of democracy, its wealth is likely to increase as well.

	
